### ISSUE TITLE
Establish connection possible.

### ISSUE THREAD

**Issue by NiklasHeneka** [mu-zero-HYPERLOOP/control-panel#68]
When the we should be able to press the connect button to connect to the pos "connecting_to_pod_possible" needs to be called by the backend first. It would be nice if it would be called on startup rightnow I just dont get it to work.

**Comment by kistenklaus** [comment]
8a93db7 should have

**Comment by NiklasHeneka** [comment]
You don't send any events yet right?

**Comment by kistenklaus** [comment]
i will check, but i think so gimmi a min

**Comment by kistenklaus** [comment]
8a93db71 should emit events. Following the rest of the architecture and to be consistant the connection_status event has to be listent to if you want i can change that and have it be listened to by default maybe a good idea. What do you think. 

Wait and there is no listen command yet ?
What seems more reasonable to you? I would be fine with both maybe a listen command is overkill i dont now?

**Comment by kistenklaus** [comment]
Interesstingly the current implementation should have a bug, where a tauri event is always broadcasted at the start.

tauri event should be:
```connection-status```

with a string as payload

**Comment by kistenklaus** [comment]
i asked @arrowtip and the conclusion is default is probably simpler so that what iam going for

**Comment by kistenklaus** [comment]
the current implementation in 7552a64a0109ba6124b941a20a1ae013d8c1c601 will broadcast the state as a tauri event called ```connection-status``` see connection.rs in cnl. However this event might be broadcasted before the react application starts and therefor is dropped by react. That's why a command called ```get_connection_status() -> ConnectionStatus``` is provided to fetch the current connection status. ```ConnectionStatus``` is serialized as a string see connection.rs on what values are allowed!

If the connection_status changes through the livetime of the application the tauri event will be broadcasted containing the ConnectionStatus as payload serialized as a string.

**Comment by NiklasHeneka** [comment]
You can take a look in[b5797d5](https://github.com/mu-zero-HYPERLOOP/control-panel/commit/b5797d5a2d33808837188758112095cd14cf7aab) at the EstablishConnection file in the frontend.
It seems that everything works now. Regarding listening I think it is best to listen from start as a default.

**Comment by kistenklaus** [comment]
i think this looks good right ? You can close if you want to =^)
