### ISSUE TITLE
ObjectEntry Struct from backend for testing.

### ISSUE THREAD

**Issue by NiklasHeneka** [mu-zero-HYPERLOOP/control-panel#74]
Having a node sending structs would be really nice to test graphs and the setting of values.

**Comment by kistenklaus** [comment]
yep working on it right now basically just have to fix some bug and test it against itself before we can test against the control panel. 

Note because for CAN virtualization we use SocketCAN this will only be possible on Linux. Sadge for Mac users. 

Alternatively a option would be to implement some sort of custom CAN virtualization based on IPC for Mac and Windows, but because i don't really use it i have to idea how IPC works on those platforms

**Comment by kistenklaus** [comment]
e74e94a changes the type of secu::global_state to a enum type see test.yaml for the variants. 
But this is not stable maybe @NiklasHeneka can check if the frontend receives reasonable data. But keep in mind that the backend on this is not tested end to end yet so the values you get might be wrong. Not sure right now would have to check myself

**Comment by kistenklaus** [comment]
done, but not merged
