### ISSUE TITLE
Add heartbeat to control panel frontend.

### ISSUE THREAD

**Issue by NiklasHeneka** [mu-zero-HYPERLOOP/control-panel#94]

**Comment by kistenklaus** [comment]
I changed it so that we walk the state machine one by one and the buttons for control change depending on the state!

So enabling the heartbeat should be the first step.

We should start at Idle.

In Idle we will not require a Heartbeat.

If we are in the Idle state we should have the button Start Heartbeat 
once pressed the heartbeat from the control panel should be enabled.

Afterwards we can press Start 45V-System to continue. or Stop Heartbeat to stop the heartbeat 
This way we can never transition into ready when the heartbeat is not active 

After precharge a heartbeat miss from the control panel will be a fatal error and will lead to an immediate system shutdown!

**Comment by kistenklaus** [comment]
All that we need is a command that is called in a interval of 100ms. You can just create a tauri command and print something there and then check if you open the dev console and execute while(true) {} if the printing stops!

**Comment by NiklasHeneka** [comment]
So right now I have a heartbeat command which is called every 100ms.
Checking the state and chaning the buttons will follow soon.
